### ISSUE TITLE
Script run twice on client

### ISSUE THREAD

**Issue by nilnullzip** [mad-eye/meteor-mocha-web#140]
Very strange. When I add mike:mocha to a project, I see the javascript executed twice in the client when the page is reloaded. This is easy to reproduce:

> meteor create --example leaderboard
> cd leaderboard
> edit leaderboard.js and insert console.log("foo") as first line
> meteor
> reload browser page and observe foo printed once on console
> meteor add mike:mocha
> meteor
> reload browser page and observe foo printed twice on console

I am running Meteor 1.0.4.1 although I think this has been an issue for earlier versions.

Adding sanjo:jasmine instead of mocha does not cause the double execution in this example. However in my larger project, it does cause double execution. Unclear if this is a Velocity or Mocha issue.
@samhatoum @Sanjo

**Comment by Atsman** [comment]
Hi, the same issue for me!

**Comment by nilnullzip** [comment]
Any ideas on whether the code is actually being run twice in the dev environment on startup? Or is this just some kind of printing issue where the test log is somehow leaking into the console?

**Comment by Atsman** [comment]
Hi, 

I think, that it is problem in iframe. Where the tests are executed. Test runner works on port 5000, where the same js works.

**Comment by rissem** [comment]
So this is happening because the client is loaded twice on that page. Once for the main app (default port 3000), and once for the mirror (port 5000). The mirror is loaded via a usually hidden iFrame on the page.

We're thinking about requiring the user to load a separate tab to see test results. If we were to do this, then you would only see one line of output in your dev server. We could also use PhantomJS instead of the browser rendering the reporter to run the client side mirror/tests. For now I'm going to close. Expect to see some alternative solutions soon.
