### ISSUE TITLE
Uncaught SecurityError when used with flow-router

### ISSUE THREAD

**Issue by rralian** [mad-eye/meteor-mocha-web#173]
I initially reported this issue within `flow-router` here https://github.com/meteorhacks/flow-router/issues/118#issuecomment-104694222. I get an error in the browser console when using velocity `meteor-mocha-web` with `flow-outer`. It appears to be an issue with `page.js` which is used within `flow-router`, and I suppose `page.js` just doesn't work within the context where `meteor-mocha-web` is running tests. I get an error that looks like this:

```bsh
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http:/?mocha=true&lastModified=1432567736395' cannot be created in a document with origin 'http://localhost:58823'.
```

Interestingly, the tests still seem to run without a problem. I don't know much about the inner workings of `meteor-mocha-web`, but it seems bizarre there would be an attempt to create a history event with the URL `http:/?mocha=true&lastModified=1432567736395`. 

This error can be reproduced with the following steps:

```bsh
$ meteor create flow-test
$ cd flow-test
$ meteor add meteorhacks:flow-router
$ meteor add mike:mocha
$ meteor
```

Has anyone else run into this? Can I just ignore that error since it doesn't appear to affect the application or the tests?

**Comment by sungwoncho** [comment]
I am experiencing the same issue. As you said, the test runs fine in spite of this. But it'd be good to have a fix for this pesky error message.

**Comment by TimFletcher** [comment]
I can confirm I'm seeing this error too.

**Comment by abernix** [comment]
I am encountering the same issue.  Since the Mocha iframe doesn't load because of the invalid origin exception being thrown, my tests actually *don't* run unless I manually go to the URL that the Mocha `iframe` is trying to load.

While the exception is happening in flow-router code, the error is caused by an invalid URL being loaded by `mike:mocha`.

The `iframe` `src` is actually combining `mirror.rootUrl + mirror.rootUrlPath` (as seen [at this line of code](https://github.com/mad-eye/meteor-mocha-web/blob/master/client.js#L50)) in the `mochaWebIFrameURL` helper.  Since `mirror.rootUrl` has a *trailing* slash and `mirror.rootUrlPath` has a *leading* slash, this is causing the `iframe` URL to be `http://localhost:56135//?mocha=true&lastModified=1440508192343` (note the double-slash after the port).

**Eliminating the double slash in the URL fixes this problem.**

I guess this can be fixed one of a few ways:

First option is changing the `mochaWebIFrameURL` helper to parse the trailing slash from `rootUrl`:
`return mirror.rootUrl.replace(/\/$/, "") + mirror.rootUrlPath + "&lastModified=" + mirror.lastModified;`

Second option, almost the same, is to use `url-join` to combine the two instead of just lobbing it off the end of the host.  This is safer, but possibly completely unnecessary because it seems the only time that rootUrlPath is set is in the server init... which brings me to the third option...

Third, **and likely best solution**, is just remove the leading slash from the `rootUrlPath` [in the server initialization code](https://github.com/mad-eye/meteor-mocha-web/blob/master/server.js#L53).  This option does require you to restart your server, as a regular hot-reload won't reinit the `velocity` database which stores this `rootUrlPath` value.

I can make a pull-request but would want @rralian to comment on if it matters changing `rootUrlPath` first, or if there is another recommended fix.

**Comment by rralian** [comment]
@abernix First, thanks for diving into this... you went deeper than I did. I don't think you need to wait for me... I'm just the guy who submitted the original issue. But your suggested fix (i.e., "best option") sounds reasonable to me. I can't think of a reason we would need the leading slash. So I'd say submit the PR.

**Comment by abernix** [comment]
Haha, well, your opinion definitely does matter, of course @rralian, but I guess I totally mis-tagged you and meant to ask the *package maintainer*, @mad-eye, if he thought changing the `rootUrlPath` would matter. :grin:

**Comment by rralian** [comment]
That's what I figured. :smile:

**Comment by frozeman** [comment]
@mad-eye could you please provide a fix as suggested (removing the `/` from `rootUrlPath`), as this makes mocha mike unusable with an app with flow-router, or page.js

**Comment by SparserLogic** [comment]
Yes, please fix this.

**Comment by abernix** [comment]
Pull-request #192 submitted which fixes this problem.

**Comment by frozeman** [comment]
:+1:
